---
# SPDX-FileCopyrightText: 2025-present Stuart Ellis <stuart@stuartellis.name>
#
# SPDX-License-Identifier: MIT
#
# Configuration for markdownlint CLI tool
#
# See: https://github.com/DavidAnson/markdownlint-cli2

config:
  # Allow multiple consecutive blank lines
  MD012: false

  # Disable maximum line-length
  MD013: false

  # Allow multiple headings with the same content
  MD024: false
