---
# SPDX-FileCopyrightText: 2025-present Stuart Ellis <stuart@stuartellis.name>
#
# SPDX-License-Identifier: MIT
#
# Configuration for pre-commit
#
# See: https://pre-commit.com

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v5.0.0"
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-json
      - id: check-toml
      - id: check-added-large-files
      - id: check-merge-conflict
        args: [--assume-in-merge]
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: "v4.0.0"
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: [--strict]
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.24.0
    hooks:
      - id: gitleaks
  - repo: https://github.com/fsfe/reuse-tool
    rev: "v5.0.2"
    hooks:
      - id: reuse
        stages: [pre-commit]
  - repo: https://github.com/rbubley/mirrors-prettier
    rev: "v3.5.3"
    hooks:
      - id: prettier
        stages: [pre-commit]
  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: "v0.17.2"
    hooks:
      - id: markdownlint-cli2
        stages: [pre-commit]
  - repo: https://github.com/adrienverge/yamllint.git
    rev: "v1.35.1"
    hooks:
      - id: yamllint
        stages: [pre-commit]
        args: [--strict]
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: "0.31.3"
    hooks:
      - id: check-github-workflows
        stages: [pre-commit]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.9.9"
    hooks:
      - id: ruff
        stages: [pre-commit]
      - id: ruff-format
        stages: [pre-commit]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.15.0"
    hooks:
      - id: mypy
        stages: [pre-commit]
  - repo: local
    hooks:
      - id: check-justfile
        name: check justfile
        entry: just
        language: system
        args: [--unstable, --fmt, --check, -f]
        files: justfile
        stages: [pre-commit]
      - id: trivy-config
        name: trivy config
        entry: trivy
        language: system
        args: [config, --exit-code, "1", .]
        pass_filenames: false
        stages: [pre-commit]
      - id: trivy-fs
        name: trivy fs
        entry: trivy
        language: system
        args: [fs, --exit-code, "1", .]
        pass_filenames: false
        stages: [pre-commit]
