---
# SPDX-FileCopyrightText: 2025-present Stuart Ellis <stuart@stuartellis.name>
#
# SPDX-License-Identifier: MIT
#
# Configuration for yamllint CLI tool
#
# See: https://yamllint.readthedocs.io

# Begin with yamllint default settings
extends: default

rules:
  comments:
    min-spaces-from-content: 1
